[build]
publish = "hugoDocs/public"
command = "rm -rf ./hugoDocs ./node_modules && mkdir .ja && mv * .ja/ && git clone --depth=1 -b japanese https://github.com/hugojapan/hugoDocs.git && cd hugoDocs && rm -rf ./content/ja && mv ../.ja ./content/ja && hugo --gc --minify --baseURL 'https://hugodocsja.netlify.com/' && echo -e 'User-agent: *\nDisallow: /' > ./public/robots.txt"

[build.environment]
HUGO_VERSION = "0.55.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NPM_FLAGS = "false"
